name: lin_reg_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - nbconvert
  - r-base
  - r-irkernel
  - r-ggplot2
  - pandas
  - matplotlib
  - scikit-learn
